apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poslite-pam.fullname" . }}-config
  labels:
    {{- include "poslite-pam.labels" . | nindent 4 }}
data:
  ierp-url: {{ .Values.config.ierpUrl | quote }}
  pam-ip: {{ .Values.config.pamIp | quote }}
  smtp-to: "mgamboa@asptg.com"
