apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poslite-cloudflared-horustech.fullname" . }}-config
  labels:
    {{- include "poslite-cloudflared-horustech.labels" . | nindent 4 }}
data:
  config.yaml: |
    tunnel: {{ .Values.config.tunnelId }}
    {{- if .Values.config.credentialsHostPath }}
    credentials-file: /etc/cloudflared/host-credentials/{{ .Values.config.tunnelId }}.json
    {{- else }}
    credentials-file: /etc/cloudflared/credentials.json
    {{- end }}
    ingress:
{{- range .Values.config.ingress }}
{{- if .hostname }}
      - hostname: {{ .hostname }}
        service: {{ .service }}
{{- else }}
      - service: {{ .service }}
{{- end }}
{{- end }}
