{{- if .Values.config.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poslite-cloudflared-horustech.fullname" . }}-credentials
  labels:
    {{- include "poslite-cloudflared-horustech.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ .Values.config.credentials | b64enc }}
{{- end }}
