apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poslite-db.fullname" . }}-secret
  labels:
    {{- include "poslite-db.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}
  pgadmin-password: {{ .Values.pgadmin.defaultPassword | b64enc | quote }}
