# Default values for poslite-db
replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "15"

pgadmin:
  enabled: true
  image:
    repository: dpage/pgadmin4
    tag: latest
  port: 5050
  hostPort: 5050
  defaultEmail: admin@admin.com
  defaultPassword: admin

postgresql:
  user: sa
  password: "z@a?ALGm^=u6[8f]Ks5]"
  database: poslite
  port: 5432
  hostPort: 5432
  timezone: "America/Panama"
  shmSize: "128mb"

persistence:
  enabled: true
  storageClass: local-path
  size: 20Gi
  accessMode: ReadWriteOnce

configMap:
  postgresqlConf: |
    listen_addresses = '*'
    shared_buffers = 512MB
    effective_cache_size = 2GB
    maintenance_work_mem = 128MB
    checkpoint_completion_target = 0.7
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 16MB
    min_wal_size = 1GB
    max_wal_size = 2GB
    max_worker_processes = 4
    max_parallel_workers_per_gather = 2
    timezone = America/Panama

serviceAccount:
  create: false

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}
