apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poslite-cloudflared-core.fullname" . }}-config
  labels:
    {{- include "poslite-cloudflared-core.labels" . | nindent 4 }}
data:
  config.yaml: |
    tunnel: {{ .Values.config.tunnelId }}
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
{{- range .Values.config.ingress }}
{{- if .hostname }}
      - hostname: {{ .hostname }}
        service: {{ .service }}
{{- else }}
      - service: {{ .service }}
{{- end }}
{{- end }}
