{{- if .Values.coreLoyaltyConfigWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "poslite-horustech.fullname" . }}-core-loyalty-config-worker
  labels:
    {{- include "poslite-horustech.labels" . | nindent 4 }}
    component: worker
    worker-type: loyalty-config
spec:
  replicas: {{ .Values.coreLoyaltyConfigWorker.replicas }}
  selector:
    matchLabels:
      {{- include "poslite-horustech.selectorLabels" . | nindent 6 }}
      component: worker
      worker-type: loyalty-config
  template:
    metadata:
      labels:
        {{- include "poslite-horustech.selectorLabels" . | nindent 8 }}
        component: worker
        worker-type: loyalty-config
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: worker
        image: "{{ .Values.imageRegistry }}/{{ .Values.imageRepository }}/{{ .Values.coreLoyaltyConfigWorker.image.repository }}:{{ .Values.coreLoyaltyConfigWorker.image.tag }}"
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
        ports:
        - name: http
          containerPort: {{ .Values.coreLoyaltyConfigWorker.port }}
          hostPort: {{ .Values.coreLoyaltyConfigWorker.hostPort }}
          protocol: TCP
        env:
        - name: TZ
          value: {{ .Values.config.timezone }}
        - name: ConnectionStrings:CoreDbConnection
          valueFrom:
            secretKeyRef:
              name: {{ include "poslite-horustech.fullname" . }}-config
              key: db-connection-string
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: GuardApi:Url
          value: "http://{{ include "poslite-horustech.guardApiService" . }}:{{ .Values.guardApi.port }}/guard/status"
        - name: CoreApiClient:BaseUrl
          value: "http://{{ include "poslite-horustech.coreWebapiService" . }}:{{ .Values.coreWebapi.port }}/"
        - name: CoreApiClient:ApiKey
          value: {{ .Values.config.coreApiKey | quote }}
        - name: IerpApi:BaseUrl
          valueFrom:
            configMapKeyRef:
              name: {{ include "poslite-horustech.fullname" . }}-config
              key: ierp-url
        - name: PROCESS
          value: "default"
        - name: Workers:LoyaltySync:CronExpression
          value: "*/5 * * * *"
        - name: Workers:LoyaltyConfig:CronExpression
          value: "0 * * * *"
        workingDir: /app
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      hostname: horustech-core-loyalty-config-worker
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
