apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poslite-horustech.fullname" . }}-config
  labels:
    {{- include "poslite-horustech.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-connection-string: "Host=poslite-db-postgres;Database=poslite;Username=sa;Password=z@a?ALGm^=u6[8f]Ks5];Trust Server Certificate=true;Include Error Detail=true;"
  smtp-password: "asp1234+"
