apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poslite-horustech.fullname" . }}-config
  labels:
    {{- include "poslite-horustech.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-connection-string: ""
  smtp-password: "asp1234+"
