apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poslite-horustech.fullname" . }}-config
  labels:
    {{- include "poslite-horustech.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-connection-string: Host=poslite-postgres-db;Port=5432;Database=poslite;Username=sa;Password=z@a?ALGm^=u6[8f]Ks5];Include Error Detail=true;
  smtp-password: "asp1234+"
